default:
  font: Helvetica
  bold: "{* Bold}"
  mono: Andale Mono
  prechap: "Chapter "
  postchap: ""
  presect: "Section "
  postsect: ""
  dql: "“"
  dqr: "”"
  con: "Contents"
  fig: "Figure "
  tab: "Table "
  indent: "\\qquad"
  thanks: "You can contact me by e-mail stefan.wintermeyer@amooma.de or via Twitter @wintermeyer"
de:
  langrule: "\\frenchspacing"
  prechap: "Kapitel "
  presect: "Abschnitt "
  fig: "Abbildung "
  tab: "Tabelle "
  con: "Inhaltsverzeichnis"
  dql: "„"
  dqr: "“"
  thanks: "You can contact me by e-mail stefan.wintermeyer@amooma.de or via Twitter @wintermeyer"
